### ISSUE TITLE
AppConnector:AppConnector(): Failed to bind local socket: Permission denied

### ISSUE THREAD

**Issue by aidakamali** [named-data/vndn#11]
When I run "./ndnd run" this error appear:
AppConnector:AppConnector(): Failed to bind local socket: Permission denied
How can I fix this error?

**Comment by Pesa** [comment]
Use `sudo` to run the programs as superuser (root).

Also, please stop asking this kind of questions here. Github issues are for reporting **bugs in the code**. It is not a support forum.
