### ISSUE TITLE
Failed to bind local socket

### ISSUE THREAD

**Issue by akakakak** [named-data/vndn#12]
If you could help me when I run ./ndnd adhoc wlan0 net 172.16.101.150 172.16.101.1 in terminal, this error show:
AppConnector:AppConnector(): Failed to bind local socket: Address already in use

**Comment by Pesa** [comment]
Make sure no other program is using the same local port. Are you running multiple instances of `ndnd` on the same machine?

**Comment by akakakak** [comment]
Thanks for the answer. 
No, I run one instance of ndnd on ubuntu.

**Comment by Pesa** [comment]
Well, check what process is using the same port with `netstat` or `ss`. Also make sure that there isn't a stale socket file around.
