### ISSUE TITLE
syntax error near unexpected token 'LIBEVEVNT,'

### ISSUE THREAD

**Issue by aidakamali** [named-data/vndn#8]
When i run "./bootstrap && make" for build, this error occured:
./configure: line 17534: syntax error near unexpected token 'LIBEVEVNT,'
./configure: line 17534: 'PKG_CHECK_MODULES(LIBEVENT, libevent)'
How can i fix this error?

**Comment by Pesa** [comment]
'LIBEVEVNT,' looks like a typo, did you touch any of the files from the repo?

Do you have `pkg-config` installed?

**Comment by aidakamali** [comment]
I install pkg-config but error not solve.
Error:
./configure: line 17534: syntax error near unexpected token 'LIBEVEVNT,'
./configure: line 17534: 'PKG_CHECK_MODULES(LIBEVENT, libevent)'

**Comment by Pesa** [comment]
As I said, "LIBEVEVNT" looks like a typo... did you modify the file `configure.ac` locally? (check with `git status`) If so, use `git checkout HEAD .`, or re-clone the repo, to restore the original version.

**Comment by aidakamali** [comment]
I did not modify the file "configure.ac"
I re-clone the repo, but error not fix.
Error:
./configure: line 17534: syntax error near unexpected token 'LIBEVEVNT,'
./configure: line 17534: 'PKG_CHECK_MODULES(LIBEVENT, libevent)'

**Comment by aidakamali** [comment]
when i run "git status" this appear:
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

**Comment by Pesa** [comment]
What's the output of `autoreconf --version`?

**Comment by aidakamali** [comment]
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

**Comment by aidakamali** [comment]
Version of autoreconf 2.69.
Please help me

**Comment by Pesa** [comment]
That's the same version I have, and it works for me. Did you install `libevent-dev`?

**Comment by aidakamali** [comment]
yes I instal libevent-2.0.20-stable, but when i run "libevent --version" the output is:
libevent: command not found

what can I do?

**Comment by aidakamali** [comment]
finally I build VNDN

**Comment by Pesa** [comment]
What was the problem?

**Comment by aidakamali** [comment]
I install software required for build again and build it.
